title: Adrian Ramirez Labor
description: "Enterprise Data Management Portfolio"
theme: jekyll-theme-minimal

logo: "https://raw.githubusercontent.com/adrianlabor19/adrianlabor19/main/Midterm%20Task%203/483918867_1585632598803121_1950398511179472480_n.jpg"


show_downloads: true
